/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayRouteImport } from './routes/play'
import { Route as ChooseRouteImport } from './routes/choose'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveDateRouteImport } from './routes/archive_.$date'

const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseRoute = ChooseRouteImport.update({
  id: '/choose',
  path: '/choose',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveDateRoute = ArchiveDateRouteImport.update({
  id: '/archive_/$date',
  path: '/archive/$date',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/choose': typeof ChooseRoute
  '/play': typeof PlayRoute
  '/archive/$date': typeof ArchiveDateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/choose': typeof ChooseRoute
  '/play': typeof PlayRoute
  '/archive/$date': typeof ArchiveDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/choose': typeof ChooseRoute
  '/play': typeof PlayRoute
  '/archive_/$date': typeof ArchiveDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/archive'
    | '/choose'
    | '/play'
    | '/archive/$date'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/archive' | '/choose' | '/play' | '/archive/$date'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/archive'
    | '/choose'
    | '/play'
    | '/archive_/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArchiveRoute: typeof ArchiveRoute
  ChooseRoute: typeof ChooseRoute
  PlayRoute: typeof PlayRoute
  ArchiveDateRoute: typeof ArchiveDateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose': {
      id: '/choose'
      path: '/choose'
      fullPath: '/choose'
      preLoaderRoute: typeof ChooseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive_/$date': {
      id: '/archive_/$date'
      path: '/archive/$date'
      fullPath: '/archive/$date'
      preLoaderRoute: typeof ArchiveDateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArchiveRoute: ArchiveRoute,
  ChooseRoute: ChooseRoute,
  PlayRoute: PlayRoute,
  ArchiveDateRoute: ArchiveDateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
